### PR TITLE
For orichters macro

### PR DESCRIPTION
**Pull request by FlorianLeblancDr**

### CODE REVIEW

**Comment by FlorianLeblancDr** [comment]
Hi @orichters
please check and accept the PR, thanks !

**Comment by danielhuppmann** [comment]
Quick jumping in here - please add the "tier" info as separate attributes for each variable, not in the file name, so that we can use it in filtering of variables lists. Also I suggest to keep the variables grouped by topic (gdp, consumption, trade) rather than by tier. We will provide a simple way to download a xlsx of variable names in a repository.

**Comment by orichters** [comment]
@danielhuppmann: I fear [this example](https://github.com/IAMconsortium/common-definitions/blob/main/definitions/variable/emissions/tag_tier1_species.yaml) was confusing to us in the first place. The `tier` here means something completely different, right? Should we just add `tier: 1` etc. to each variable?

**Comment by danielhuppmann** [comment]
Apologies, I see why the different use of tier was confusing. And yes, for the time being, please add `tier: 1` to all variables individually - at the same time, you can make the variable-lists a lot shorter by using the tag-lists.

**Comment by FlorianLeblancDr** [comment]
Thanks for the precision Daniel, I was gonna raise an issue on this as I was also wondering how to report Tiers, as Volker asked as a first assignment to provide a list of tier 1 variable.

Also agreed to keep the variables grouped by topic.
I found it useful to make a first proposition in a single file, just to coordinate the discussion within the sub-group and stick on github (and avoid discussion on email, excel, etc.), then split it later

**Comment by orichters** [comment]
- Dear @FlorianLeblancDr: Thanks for your work!
- I found it easier to just add the variables you suggest to my branch so Consumption, Trade etc. stay together and I did not have to undo the split. So you find it here: https://github.com/IAMconsortium/common-definitions/commit/151432f5fe47d3dad4fc378fb3fe05f6223964c3
- So I think we can close here.

**Pull request closed without merging**
